

# Almost all the things in the website can be customized from here.
# Changing title and description according to your website requirement is important.


title: Aditya Amatya
description: A personal Portfolio
url: https://adityaamatya.com.np

baseurl: ""

# buy-link: 
#   rzp: https://rzp.io/l/blackcurrant-theme
#   pp: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=5TM7X9TE7KMKN
# # For more customizations, go to  _data/main.yml

# Kramdown is the default markdown processor used. It is supported by Github.
markdown: kramdown

# Mathjax setting
enable-mathjax: yes

# Charts
enable-chartjs: yes


# This defines how the URLs should look like.
permalink: /blog/:title/

# Pagination - Posts per page in the blog index.
paginate: 6
paginate_path: /blog/page:num/


# Jekyll will read contents inside _pages only if we tell it to.
include:
    - _pages

# Google Ananlytics Tracker.
# Sign up with Google analytics and replace with your analytics ID.
analytics: G-VH8HKD81EQ

# Table of contents in each post
# Change the value to 'no' if Table of Contents is not required.
toc:  yes

# Share buttons
# Change it to `no` to remove share buttons.
share: yes


# Comments by Disqus
# Sign up with Disqus to get your shortcode. Leave it blank if you do not want to run diqus code on the website.
# Leave it blank to remove disqus completely.
disqus: https://https-amatya-aditya-github-io


# Define whether recent posts should be shown at the bottom of each post.
# Change it to `no` to remove recent posts.
recent-posts: yes



# Editing items below this line can break the site
##################################################


#
#   ,-----.                                                    ,--.
#  '  .--./ ,---. ,--,--,--. ,---. ,--.--. ,---.  ,---.  ,---. `--' ,---. ,--,--,
#  |  |    | .-. ||        || .-. ||  .--'| .-. :(  .-' (  .-' ,--.| .-. ||      \
#  '  '--'\' '-' '|  |  |  || '-' '|  |   \   --..-'  `).-'  `)|  |' '-' '|  ||  |
#   `-----' `---' `--`--`--'|  |-' `--'    `----'`----' `----' `--' `---' `--''--'
#                           `--'
# All compression variables are declared here.

sass:
 sass_dir: /assets/css/_sass
 style: compressed

#compress.html
compress_html:
  clippings: [html, head, meta, title, link, body, div, script, header, footer]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []


collections:
    projects:
        output: true
        permalink: /projects/:path/

    articles:
        output: true
        permalink: /articles/:path/

    personal:
        output: true
        permalink: /personal/:path/

    portfolio:
        output: true
        permalink: /portfolio/:path/

exclude:
    - .git
    - vendor
    - .obsidian
    - .forestry
    - .vscode


# These plugins are supported by github by default and can be installed locally using ruby gems
plugins:
    - jekyll-sitemap    # Adds sitemap to the website at /sitemap.xml
    - jekyll-feed       # Adds feed to the website at /feed.xml
    - jekyll-paginate   # Used for sorting posts by page numbers.
    - jekyll-seo-tag    # Adds all the important SEO meta tags by default.
    # - jekyll-responsive-image    # Adds responsive images automatically.
    # - rmagick


responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html #THIS ONE
# [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 90
# [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 320
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800
    - width: 1400
      quality: 90
# [Optional, Default: false]
  # Rotate resized images depending on their EXIF rotation attribute. Useful for
  # working with JPGs directly from digital cameras and smartphones
  auto_rotate: false
# [Optional, Default: false]
  # Strip EXIF and other JPEG profiles. Helps to minimize JPEG size and win friends
  # at Google PageSpeed.
  strip: true
# [Optional, Default: assets]
  # The base directory where assets are stored. This is used to determine the
  # `dirname` value in `output_path_format` below.
  base_path: uploads
# [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{dirname}     Directory of the file relative to `base_path` (assets/sub/dir/some-file.jpg => sub/dir)
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: assets/resized/%{width}/%{basename}
# [Optional, Default: true]
  # Whether or not to save the generated assets into the source folder.
  save_to_source: false
# [Optional, Default: false]
  # Cache the result of {% responsive_image %} and {% responsive_image_block %}
  # tags. See the "Caching" section of the README for more information.
  cache: false
# [Optional, Default: []]
  # By default, only images referenced by the responsive_image and responsive_image_block
  # tags are resized. Here you can set a list of paths or path globs to resize other
  # images. This is useful for resizing images which will be referenced from stylesheets.
  extra_images:
    - uploads/*/*/*/*.{jpeg,jpg}